language: ruby

rvm:
  - 2.2

before_script:
  - gem install awesome_bot

script:
  - awesome_bot README.md --skip-save-results --allow-redirect --white-list https://www.linkedin.com/jobs/devops-jobs
